{% set version = "1.23" %}
{% set hash = "9a37f8a6174f09bd622bc723b55881dc541cd50747cbd08831c2a82d620f6d76" %}

package:
  name: leveldb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/google/leveldb/archive/{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
    0001-dont-disable-rtti.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - snappy
  run:
    - snappy

test:
  commands:
    - test -f ${PREFIX}/lib/libleveldb${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\leveldb.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\lib\\leveldb.lib exit 1          # [win]

about:
  home: https://github.com/google/leveldb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A fast key-value storage library providing ordered mappings.

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
