{% set version = "1.20" %}

package:
  name: leveldb
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/google/leveldb/archive/v{{ version }}.tar.gz
  sha1: f5abe8b5b209c2f36560b75f32ce61412f39a2922f7045ae764a2c23335b6664

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - snappy

  run:
    - snappy

test:
  commands:
    - test -f ${PREFIX}/lib/libmemenv.a
    - test -f ${PREFIX}/lib/libleveldb.dylib            # [osx]
    - test -f ${PREFIX}/lib/libleveldb.so               # [linux]

about:
  home: https://github.com/google/leveldb
  license: BSD
  summary: A fast key-value storage library providing ordered mappings.

extra:
  recipe-maintainers:
    - jakirkham
